n=input('digite algo')
print ('o tipo primitivo é ', type(n))
print ('tem espaços  ',n.isspace()) 
print ('esta capitalizado ',n.istitle())
print ('é alfabetico ',n.isalpha())
print ('é numerico ',n.isnumeric())
print ('e alfanumerico ',n.isalnum())
print ('ésta em maiuscolas ',n.isupper())
print ('ésta em minuscolas ',n.islower())
